# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\bakalavr\diplom\mycloud\ui\settings_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(414, 150)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 391, 111))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.saveSettings_btn = QtWidgets.QPushButton(self.groupBox)
        self.saveSettings_btn.setGeometry(QtCore.QRect(10, 70, 371, 31))
        self.saveSettings_btn.setObjectName("saveSettings_btn")
        self.path_txt = QtWidgets.QTextEdit(self.groupBox)
        self.path_txt.setGeometry(QtCore.QRect(10, 30, 281, 21))
        self.path_txt.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.path_txt.setObjectName("path_txt")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 10, 211, 16))
        self.label.setObjectName("label")
        self.browseLocalPath_btn = QtWidgets.QPushButton(self.groupBox)
        self.browseLocalPath_btn.setGeometry(QtCore.QRect(300, 20, 81, 31))
        self.browseLocalPath_btn.setObjectName("browseLocalPath_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 414, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Настройки"))
        self.saveSettings_btn.setText(_translate("MainWindow", "Сохранить"))
        self.label.setText(_translate("MainWindow", "Путь к папке на локальном диске"))
        self.browseLocalPath_btn.setText(_translate("MainWindow", "Обзор"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
