# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\bakalavr\diplom\mycloud\settings_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5 import QtCore, QtGui, QtWidgets
import funcs as f
import auth_form
import cloud_storage_form

class Ui_MainWindow(object):
    dirlist = f.get_val_in_local_storage('local_path')

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(414, 232)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 90, 391, 111))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.saveSettings_btn = QtWidgets.QPushButton(self.groupBox)
        self.saveSettings_btn.setGeometry(QtCore.QRect(10, 70, 371, 31))
        self.saveSettings_btn.setObjectName("saveSettings_btn")
        self.path_txt = QtWidgets.QTextEdit(self.groupBox)
        self.path_txt.setGeometry(QtCore.QRect(10, 30, 281, 21))
        self.path_txt.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.path_txt.setObjectName("path_txt")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 10, 211, 16))
        self.label.setObjectName("label")
        self.browseLocalPath_btn = QtWidgets.QPushButton(self.groupBox)
        self.browseLocalPath_btn.setGeometry(QtCore.QRect(300, 20, 81, 31))
        self.browseLocalPath_btn.setObjectName("browseLocalPath_btn")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 391, 71))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.current_user = QtWidgets.QLabel(self.groupBox_2)
        self.current_user.setGeometry(QtCore.QRect(10, 10, 361, 16))
        self.current_user.setText("")
        self.current_user.setObjectName("current_user")
        self.change_user_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.change_user_btn.setGeometry(QtCore.QRect(10, 32, 371, 31))
        self.change_user_btn.setObjectName("change_user_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 414, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.set_current_user()
        self.change_user_btn.clicked.connect(self.logout)
        #self.change_user_btn.clicked.connect(cloud_storage_form.close_cs_form)
        self.change_user_btn.clicked.connect(MainWindow.close)
        self.browseLocalPath_btn.clicked.connect(self.set_local_directory)
        self.load_local_directory()
        self.saveSettings_btn.clicked.connect(self.confirm_settings)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.saveSettings_btn.setText(_translate("MainWindow", "Сохранить"))
        self.label.setText(_translate("MainWindow", "Путь к папке на локальном диске"))
        self.browseLocalPath_btn.setText(_translate("MainWindow", "Обзор"))
        self.change_user_btn.setText(_translate("MainWindow", "Сменить пользователя"))

    def set_current_user(self):
        try:
            current_user = f.get_val_in_local_storage('login')
            self.current_user.setText("Текущий пользователь: "+current_user)
        except Exception:
            pass

    def open_auth_form(self):
        self.window = QMainWindow()
        self.ui = auth_form.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def close_cs_form(self):
        cs_ui = cloud_storage_form.Ui_MainWindow()
        cs_ui.close_cloud_storage_form()

    def logout(self):
        #f.put_val_in_local_storage('service_acc_id','')
        #f.put_val_in_local_storage('static_key_id','')
        #f.put_val_in_local_storage('static_secret_key','')
        #f.put_val_in_local_storage('login','')
        self.open_auth_form()

    def load_local_directory(self):
        local_path = f.get_val_in_local_storage('local_path')
        self.path_txt.setText(local_path)

    def set_local_directory(self):
        self.dirlist = QFileDialog.getExistingDirectory(None, "Выбрать папку", ".")+'/'
        self.path_txt.setText(self.dirlist)

    def confirm_settings(self):
        f.put_val_in_local_storage('local_path', self.dirlist)
        f.ShowMessageBox('Успешно','Локальный путь '+self.dirlist+' сохранен')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
